# Generated by Django 5.1.4 on 2024-12-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faunatrack", "0002_gps_espece_status_alter_espece_nom_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilscientifique",
            name="domaine_de_recherche",
            field=models.CharField(default="", max_length=255),
        ),
    ]
