# Generated by Django 5.1.4 on 2024-12-17 14:28

import faunatrack.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faunatrack", "0003_profilscientifique_domaine_de_recherche"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gps",
            options={"verbose_name": "GPS", "verbose_name_plural": "GPS"},
        ),
        migrations.AlterModelOptions(
            name="profilscientifique",
            options={
                "verbose_name": "Profil scientifique",
                "verbose_name_plural": "Profils scientifique",
            },
        ),
        migrations.AlterField(
            model_name="gps",
            name="latitude",
            field=models.DecimalField(
                decimal_places=5,
                max_digits=8,
                validators=[faunatrack.validators.validate_latitude],
            ),
        ),
        migrations.AlterField(
            model_name="gps",
            name="longitude",
            field=models.DecimalField(
                decimal_places=5,
                max_digits=8,
                validators=[faunatrack.validators.validate_longitude],
            ),
        ),
    ]
