# Generated by Django 5.1.4 on 2024-12-18 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "faunatrack",
            "0004_alter_gps_options_alter_profilscientifique_options_and_more",
        ),
    ]

    def func(self):
        pass
        # User.objects.create_superuser()

    operations = [migrations.RunPython(func),]
